name: sinonimo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  csv: ^6.0.0
  get: ^4.6.6
  shared_preferences: ^2.3.4  
  google_fonts: ^6.2.1 
  uuid: ^4.5.1
  just_audio: ^0.9.42
  package_info_plus: ^8.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true
  assets:
    - assets/sinonimos.csv
    - assets/dados.json
    - assets/fundo.png
    - assets/musica_de_fundo.mp3
    - assets/som_acerto.mp3
    - assets/som_erro.mp3
    - assets/uil_padlock.png


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
